[package]
name = "rust-calculator-gui"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
gtk = { version = "0.9.4", package = "gtk4", features = ["v4_16"] }

[build-dependencies]
glib-build-tools = "0.20.0"
